export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOG_OUT = 'LOG_OUT';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOAD_PROFILE = 'LOAD_PROFILE';

export const HOME_VIDEOS_REQUEST = 'HOME_VIDEOS_REQUEST';
export const HOME_VIDEOS_SUCCESS = 'HOME_VIDEOS_SUCCESS';
export const HOME_VIDEOS_FAILURE = 'HOME_VIDEOS_FAILURE ';
export const SELECT_VIDEO_REQUEST = 'SELECT_VIDEO_REQUEST';
export const SELECT_VIDEO_SUCCESS = 'SELECT_VIDEO_SUCCESS';
export const SELECT_VIDEO_FAILURE = 'SELECT_VIDEO_FAILURE';

export const CHANNEL_DETAIL_REQUEST = 'CHANNEL_DETAIL_REQUEST';
export const CHANNEL_DETAIL_SUCCESS = 'CHANNEL_DETAIL_SUCCESS';
export const CHANNEL_DETAIL_FAILURE = 'CHANNEL_DETAIL_FAILURE';

export const CHECK_SUBSCRIPTION_REQUEST = 'CHECK_SUBSCRIPTION_REQUEST';
export const CHECK_SUBSCRIPTION_SUCCESS = 'CHECK_SUBSCRIPTION_SUCCESS';
export const CHECK_SUBSCRIPTION_FAILURE = 'CHECK_SUBSCRIPTION_FAILURE';

export const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUEST';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAILURE = 'GET_COMMENTS_FAILURE';

export const ADD_COMMENT_SUCCESS = 'ADD_COMMENT_SUCCESS';
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE';

export const RELATED_VIDEOS_REQUEST = 'RELATED_VIDEOS_REQUEST';
export const RELATED_VIDEOS_SUCCESS = 'RELATED_VIDEOS_SUCCESS';
export const RELATED_VIDEOS_FAILURE = 'RELATED_VIDEOS_FAILURE';

export const SEARCH_VIDEOS_REQUEST = 'SEARCH_VIDEOS_REQUEST';
export const SEARCH_VIDEOS_SUCCESS = 'SEARCH_VIDEOS_SUCCESS';
export const SEARCH_VIDEOS_FAILURE = 'SEARCH_VIDEOS_FAILURE';

export const SUBSCIBED_CHANNEL_REQUEST = 'SUBSCIBED_CHANNEL_REQUEST';
export const SUBSCIBED_CHANNEL_SUCCESS = 'SUBSCIBED_CHANNEL_SUCCESS';
export const SUBSCIBED_CHANNEL_FAILURE = 'SUBSCIBED_CHANNEL_FAILURE';

export const CHANNEL_VIDEOS_REQUEST = 'CHANNEL_VIDEOS_REQUEST';
export const CHANNEL_VIDEOS_SUCCESS = 'CHANNEL_VIDEOS_SUCCESS';
export const CHANNEL_VIDEOS_FAILURE = 'CHANNEL_VIDEOS_FAILURE';

export const PLAYLIST_REQUEST = 'PLAYLIST_REQUEST';
export const PLAYLIST_SUCCESS = 'PLAYLIST_SUCCESS';
export const PLAYLIST_FAILURE = 'PLAYLIST_FAILURE';

export const CHECK_RATING_REQUEST = 'CHECK_RATING_REQUEST';
export const CHECK_RATING_SUCCESS = 'CHECK_RATING_SUCCESS';
export const CHECK_RATING_FAILURE = 'CHECK_RATING_FAILURE';
